# Generated by Django 5.1.7 on 2025-05-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='false_options',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='challenge',
            name='type',
            field=models.CharField(choices=[('author', 'Author'), ('title', 'Title')], default='title', max_length=10),
        ),
    ]
