# Generated by Django 5.1.7 on 2025-05-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_challenge_false_options_challenge_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weekly_points',
            field=models.IntegerField(default=0),
        ),
    ]
