# Generated by Django 5.1.7 on 2025-05-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_daily_points_user_monthly_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeset',
            name='category',
            field=models.CharField(choices=[('author', 'Author'), ('title', 'Title')], default='title', max_length=10),
        ),
    ]
