# Generated by Django 5.1.7 on 2025-05-30 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_track_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='track',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='challengeset',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_sets', to=settings.AUTH_USER_MODEL),
        ),
    ]
