# Generated by Django 5.1.7 on 2025-06-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_challenge_track_alter_challengeset_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeset',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
