# Generated by Django 5.1.7 on 2025-06-06 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_challengeset_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='Challenge',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='time_taken',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='genre',
        ),
        migrations.AddField(
            model_name='attempt',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attempt',
            name='challenge_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.challengeset'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GameRoom',
        ),
    ]
