# Generated by Django 5.1.7 on 2025-06-06 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_attempt_challenge_remove_attempt_answer_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.BigIntegerField()),
                ('score', models.IntegerField()),
                ('tips_used', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='random_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
