# Generated by Django 5.1.7 on 2025-06-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_randomattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
